docs update for table primitive, use theme values, use exampleCode co…
aws-amplify/amplify-ui pull request #1202
Opened 2022-01-27 10:13 UTC by jacoblogan

*Issue #944

*Description of changes: Update to the docs Table component, update examples, use theme values.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-02-09 22:54 UTC, zchenwei requested changes
Looking good. Left a few comments :)

2022-02-09 22:54 UTC, zchenwei commented on docs/src/pages/components/table/examples/index.ts
>  export { BasicExample } from './basicExample';
Could we update the old file names to be Pascal case?

2022-02-09 22:54 UTC, zchenwei commented on docs/src/pages/components/table/TablePropControls.tsx
> +import { DemoBox } from '@/components/DemoBox';
We need to get rid of `DemoBox` in favor of `Demo` and show code generation

2022-02-17 19:12 UTC, jacoblogan commented on docs/src/pages/components/table/TablePropControls.tsx
> +  <Flex direction="column">
Yes good catch, thanks!

2022-02-23 23:02 UTC, zchenwei approved these changes
LGTM! :shipit:

2022-02-24 00:09 UTC, dbanksdesign approved these changes

2022-02-24 08:37 UTC, merged