Added Indonesian translation.
aws-amplify/amplify-ui pull request #1439
Opened 2022-03-01 20:48 UTC by artidata

#### Description of changes

Added translation for the authenticator and cognito error messages.

#### Issue #, if available

#### Description of how you validated changes

I'm using it for my website, cross checking it with translation tools.

#### Checklist

- [ ] PR description included
- [ ] `yarn test` passes
- [ ] Tests are updated
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-03-02 09:51 UTC, wlee221 commented on packages/ui/src/i18n/translations.ts
> +  idDict,
You should add `idDict` to  `translations` variable in line 76:
https://github.com/aws-amplify/amplify-ui/blob/a9ca442f4d005a597c84a326baf18b4e9bbe78c2/packages/ui/src/i18n/translations.ts#L76-L78

2022-03-02 09:54 UTC, wlee221 requested changes
Thanks for your contribution @artidata! Can you: 
- address https://github.com/aws-amplify/amplify-ui/pull/1439/files#r817523250
- Update our docs (this [file](https://github.com/eli6/amplify-ui/blob/main/docs/src/pages/components/authenticator/index.page.mdx#internationalization-i18n), line 417) to include Indonesian as supported language. Languages below English are listed alphabetically.

2022-03-02 18:38 UTC, artidata commented
@wlee221, I made the changes. Let me know if I got it right.

2022-03-02 22:20 UTC, reesscot commented
@artidata Looking good, just missing docs changes mentioned by @wlee221:

> Update our docs (this [file](https://github.com/eli6/amplify-ui/blob/main/docs/src/pages/components/authenticator/index.page.mdx#internationalization-i18n), line 417) to include Indonesian as supported language. Languages below English are listed alphabetically.

2022-03-02 22:42 UTC, artidata commented
@reesscot It's in a separate pull request, because the its merging to different fork by eli6, as that link refers to: https://github.com/eli6/amplify-ui/pull/1/commits. Should it be this file then: https://github.com/aws-amplify/amplify-ui/blob/main/docs/src/pages/components/authenticator/customization.i18n.web.mdx.

2022-03-03 00:00 UTC, wlee221 approved these changes
Looks good, really appreciate your language contribution 🙏

2022-03-03 17:38 UTC, reesscot approved these changes

2022-03-03 18:01 UTC, merged