Vendor prefix
aws-amplify/amplify-ui pull request #183
Opened 2021-08-12 20:22 UTC by jacoblogan

This pull request will use autoprefixer to add vendor prefixes to both the static styling and and inline styling for amplify theming and primitive styling.

The render-time inline styling all runs through the view component style prop, this includes both the developer defined style props passed into primitives through the style prop and also the amplify styling props such as `color`, `fontWeight`, etc.  So by wrapping the style object we compute with the autoprefixer function, we will catch almost all instances of inline styling.  Some css in js libraries will avoid this by creating class names at run time, but most css in js libraries also handle vendor prefixes.

2021-08-16 17:58 UTC, zchenwei commented on packages/react/src/primitives/View/View.tsx
> +const prefixer = postcssJs.sync([autoprefixer]);
I feel like it makes more sense to put the logic inside a util function and then import that function to use here. What do you think?

2021-08-16 18:34 UTC, zchenwei commented on packages/react/src/primitives/View/View.tsx
> +const prefixer = postcssJs.sync([autoprefixer]);
Or maybe could wrap it outside `convertStylePropsToStyleObj`

2021-08-16 18:39 UTC, zchenwei requested changes
Looks good! Just a small comment

2021-08-17 16:34 UTC, reesscot commented on packages/react/src/primitives/shared/utils.ts
> +import postcssJs from 'postcss-js';
nit: mind moving external imports to the top of the file?

2021-08-17 16:34 UTC, reesscot submitted a review, later dismissed
LGTM!

2021-08-17 16:40 UTC, zchenwei approved these changes
LGTM!

2021-08-18 19:05 UTC, reesscot approved these changes

2021-08-18 19:16 UTC, merged

2021-12-07 03:19 UTC, jaminmelville commented
Hey @jacoblogan I'm trying to find out why my bundled JS is so large. It looks like the `autoprefixer` package is contributing significantly, as it has a dependency on `caniuse-lite` which is 1.44MB. 
I'm guessing that this may be an issue for me as I haven't found any related issues in github. 
Can you shed any light?
Thanks!