feat(ui-react-native): Add theming for Radio primitive
aws-amplify/amplify-ui pull request #2913
Opened 2022-11-08 18:13 UTC by joebuono

#### Description of changes

https://user-images.githubusercontent.com/48109584/200642886-a654ffc8-0b9f-4879-87b7-5592e2061337.mov

#### Issue #, if available

#### Description of how you validated changes

Ran in iOS and Android, and updated unit tests. 

#### Checklist

- [X] PR description included
- [X] `yarn test` passes
- [X] Tests are updated

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-11-08 19:02 UTC, ioanabrooks reviewed
Great work! Overall lgtm but I think styling needs a little more love, especially for the different sizes. We should have different border widths for each radio size, and the border seems to be getting further and further away from the dot as the size of the radio increases (look and feel should be consistent and proportional to radio size)

2022-11-08 21:04 UTC, calebpollman requested changes

2022-11-08 21:04 UTC, calebpollman commented on packages/react-native/src/primitives/Radio/getRadioDimensions.ts
> +        borderWidth: Math.floor(size / 10) - 1,
Called this out in the thread, but i think the `borderWidth` should be stable across our `Size` variants. It is very easy for users to make changes if they choose to

2022-11-08 21:04 UTC, calebpollman commented on packages/react-native/src/primitives/Radio/getRadioDimensions.ts
> +        borderWidth: Math.floor(size / 10) - 1,
See https://github.com/aws-amplify/amplify-ui/pull/2913#discussion_r1017099842

2022-11-08 21:12 UTC, ioanabrooks commented on packages/react-native/src/primitives/Radio/styles.ts
> +      borderWidth: 2,
Any particular reason why it should be the same, 2 looks too thick to me for the small variant.

2022-11-08 23:13 UTC, calebpollman commented on packages/react-native/src/primitives/Radio/styles.ts
> +      borderWidth: 2,
A `borderWidth` of `1` looks very thin for the `small` variant:

<img src="https://user-images.githubusercontent.com/15002885/200694474-627d4299-2c49-4a57-8ba5-f437229eb527.png" alt="" width="300"/>

If we bump the `borderWidth` on the `large`  to `3`, think that might looks a bit better due to the decrease in white space around the dot, but looks too thick when the `Radio` is unselected and alos when compared to the default `fontWeight` of the `Label`:

<img src="https://user-images.githubusercontent.com/15002885/200694854-ba8b06ef-ff71-4df8-a3be-8948da3fd260.png" alt="" width="300"/>

Preference is to keep the `borderWidth` at `2`, and slightly increase the dot dimensions on the `large` variant:



<img src="https://user-images.githubusercontent.com/15002885/200695653-d85b9722-33cf-412c-b22e-5fe245cc0397.png" alt="" width="300"/>

2022-11-08 23:31 UTC, joebuono commented on packages/react-native/src/primitives/Radio/styles.ts
> +      borderWidth: 2,
@dbanksdesign Thoughts?

2022-11-09 19:14 UTC, ioanabrooks commented on packages/react-native/src/primitives/Radio/styles.ts
> +      backgroundColor: colors.teal[80],
This should reference `colors.brand.primary[80]`

2022-11-09 19:18 UTC, ioanabrooks commented on packages/react-native/src/primitives/Radio/getRadioDimensions.ts
> +export const RADIO_DOT_PROPORTION = 0.6;
Nice! Conjugate golden ratio.  Would be nice to add a comment on why we landed on this value or purpose to help future readers.

2022-11-09 20:45 UTC, ioanabrooks commented on packages/react-native/src/primitives/Radio/getRadioDimensions.ts
> +export const RADIO_DOT_PROPORTION = 0.6;
The Silver Ratio! :)

2022-11-09 20:46 UTC, ioanabrooks approved these changes

2022-11-09 22:40 UTC, calebpollman approved these changes

2022-11-09 22:43 UTC, merged