docs: Add missing angular documentation
aws-amplify/amplify-ui pull request #322
Opened 2021-09-01 16:33 UTC by wlee221

*Issue #, if available:*

*Description of changes:* Adds missing angular markdowns. 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-09-01 16:36 UTC, wlee221 commented on docs/src/pages/ui/components/authenticator/headless.angular.mdx
> +  constructor(private stateMachine: StateMachineService) {}
This service will likely be changed with a more publicly facing API, e.g. `AuthenticatorService`.

2021-09-01 16:36 UTC, wlee221 commented on examples/angular/src/app/app.module.ts
> +// TODO: Rename UiAngularModule to AmplifyUiAngularModule
Noticed my angular module is named too generally. Will add a PR by this week.

2021-09-01 19:59 UTC, ErikCH requested changes
Just 2 quick nit picks. 

The links in the Angular documentation for source directs to Githubs 404 page. The Demo and Test work however. I believe this is because the examples app uses a different directory structure.

![image](https://user-images.githubusercontent.com/65630/131735256-38e02a07-fbc7-4e64-bb33-e8072af415da.png)

And the first example for getting started, doesn't actually show wrapping the template with `amplify-authenticator`. Instead it shows how to install it in the app module. Maybe it should show both?

2021-09-01 22:32 UTC, wlee221 commented
Re: @ErikCH,

> The links in the Angular documentation for source directs to Githubs 404 page.

Fixed in https://github.com/aws-amplify/amplify-ui/pull/322/commits/d5b45d04783f3b5f82372120dc4727c0c1d54fc8.

> And the first example for getting started, doesn't actually show wrapping the template with amplify-authenticator. 

Can't believe I missed this 🤦  Thanks for the catch! Done in https://github.com/aws-amplify/amplify-ui/pull/322/commits/63788dfbf4effb9d49f649aa6f6aa8e981e85f25.

2021-09-01 23:15 UTC, ErikCH approved these changes
Looks good!

2021-09-02 18:39 UTC, wlee221 commented on docs/src/pages/ui/components/authenticator/getting-started.angular.mdx
> +  <ng-template amplifySlot="authenticated" let-user="user">
```suggestion
  <ng-template
    amplifyOverride="authenticated"
    let-user="user"
    let-signOut="signOut"
  >
```

2021-09-02 20:28 UTC, merged