Add missing dutch translations
aws-amplify/amplify-ui pull request #3476
Opened 2023-02-26 20:44 UTC by buremer

#### Description of changes

Addresses some missing translations in Authenticator for the Dutch language.

#### Issue #, if available

#### Description of how you validated changes

Had to use this in an external project. That's how I found out that some are missing and fixed them first in that project directly, before creating a PR here.

#### Checklist

- [x] PR description included
- [ ] `yarn test` passes

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-02-27 16:43 UTC, reesscot approved these changes
Thank you for your contribution!

2023-02-27 16:55 UTC, ioanabrooks submitted a review, later dismissed

2023-02-27 16:58 UTC, calebpollman requested changes
Thanks for adding these @buremer

Since some of these keys are not supported in our existing translations will need to discuss internally before we can merge

2023-02-28 10:55 UTC, buremer commented
@calebpollman No problem! Just to mention, these keys come straight from the Cognito Api call in this format and have been tested using the `I18n.putVocabularies` from `aws-amplify` package.

2023-03-03 00:21 UTC, calebpollman reviewed
Thanks for your contribution and patience on getting this merged @buremer 

As noted in the PR, some of the translation keys are not controlled by Amplify UI (they come directly from [Amazon Cognito](https://aws.amazon.com/cognito/)) so we can not include them in our translations by default. If you can remove those keys we can get this merged asap. 

For your awareness, we are definitely looking in to how to better support custom error messages in the future!

2023-03-03 00:21 UTC, calebpollman commented on packages/ui/src/i18n/dictionaries/authenticator/nl.ts
> +  'Attributes did not conform to the schema: email: The attribute is required\n':
Unfortunately we do not have control over this message and cannot include this key in our translations

2023-03-03 00:21 UTC, calebpollman commented on packages/ui/src/i18n/dictionaries/authenticator/nl.ts
> +    'Wachtwoord voldoet niet aan de vereisten: Wachtwoord is niet lang genoeg',
Similar to the above comment, unfortunately we do not have control over these messages and cannot include the keys in our translations

2023-03-03 14:05 UTC, buremer commented
Aha! Ok thanks for clarifying @calebpollman. I wasn't sure what you meant with that it's not supported. I've removed the keys for now. If there's more I need to change, please let me know ✌️

2023-03-03 17:12 UTC, reesscot approved these changes

2023-03-03 17:13 UTC, merged