fix: Update override function calls reference to v6
aws-amplify/amplify-ui pull request #4872
Opened 2023-12-26 19:43 UTC by nadetastic

#### Description of changes

The override function calls for Authenticator reference APIs as they appear in v5 of `aws-amplify`. This PR updates them to reference usage in v6.
- https://ui.docs.amplify.aws/react/connected-components/authenticator/customization#override-function-calls

#### Issue #, if available
N/A

#### Description of how you validated changes

#### Checklist

- [ ] Have read the [Pull Request Guidelines](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md)
- [ ] PR description included
- [ ] Relevant documentation is changed or added (and PR referenced)
- [ ] `yarn test` passes and tests are updated/added
- [ ] No side effects or [`sideEffects`](https://github.com/aws-amplify/amplify-ui/blob/main/packages/react/CONTRIBUTING.md#code-standards) field updated

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-12-27 20:21 UTC, esauerbo commented on docs/src/pages/[platform]/connected-components/authenticator/customization/customization.override-function-calls.web.mdx
> +      <ResponsiveTableCell label="Function Call">`resettPassword()`</ResponsiveTableCell>
```suggestion
      <ResponsiveTableCell label="Function Call">`resetPassword()`</ResponsiveTableCell>
```

2023-12-27 20:25 UTC, esauerbo commented
Thanks for doing this! One suggestion but otherwise LGTM

2023-12-29 17:22 UTC, esauerbo submitted a review, later dismissed

2024-01-02 17:14 UTC, reesscot requested changes
We shouldn't fully remove this from the UI docs since most customers will still be using v5. We should show both versions on the page in a Tabs component.

2024-01-02 18:53 UTC, calebpollman requested changes

2024-01-02 18:53 UTC, calebpollman commented on docs/src/pages/[platform]/connected-components/authenticator/customization/customization.override-function-calls.react-native.mdx
> +      <ResponsiveTableCell label="Function Call">`signUp()`</ResponsiveTableCell>
Let's remove the parans on the function names, that is not a pattern that has been used in the UI docs previously, nor does it provide the correct input for the functions

2024-01-03 22:15 UTC, nadetastic commented on docs/src/pages/[platform]/connected-components/authenticator/customization/customization.override-function-calls.react-native.mdx
> -      <ResponsiveTableCell label="Function Call">`Auth.signUp`</ResponsiveTableCell>
Pushed a commit that adds a v5 column @reesscot how does this look?

2024-03-13 09:00 UTC, isaaccarrington commented on docs/src/pages/[platform]/connected-components/authenticator/customization/overrides/username.react.mdx
>        attributes.email = attributes.email.toLowerCase();
Can you add amend this to `options.userAttributes.email = options.userAttributes.email.toLowerCase();` please?

2024-08-06 14:22 UTC, esauerbo commented
We updated the tables to reference v6 in https://github.com/aws-amplify/amplify-ui/pull/5153 and https://github.com/aws-amplify/amplify-ui/pull/5150, closing this out

2024-08-06 14:22 UTC, closed without merging