Update ja.ts
aws-amplify/amplify-ui pull request #5054
Opened 2024-03-10 09:12 UTC by sj-h4

#### Description of changes

In `<authenticator>`, 'Enter your Username' is used instead of 'Enter your username', so I added a Japanese translation for 'Enter your Username'.

#### Issue #, if available

#### Description of how you validated changes

#### Checklist

- [x] Have read the [Pull Request Guidelines](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md)
- [x] PR description included
- [x] Relevant documentation is changed or added (and PR referenced)
- [x] `yarn test` passes and tests are updated/added
- [x] No side effects or [`sideEffects`](https://github.com/aws-amplify/amplify-ui/blob/main/packages/react/CONTRIBUTING.md#code-standards) field updated

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-03-11 21:08 UTC, esauerbo requested changes
@sj-h4 thank you for your contribution! Left a few comments.

2024-03-11 21:08 UTC, esauerbo commented on packages/ui/src/i18n/dictionaries/authenticator/ja.ts
> +  'Enter your Username': 'ユーザー名を入力 ',
I may be wrong but this looks the same as the original string, maybe a copy/paste error?

2024-03-11 21:08 UTC, esauerbo commented on packages/ui/src/i18n/dictionaries/authenticator/ja.ts
>    'Enter your username': 'ユーザー名を入力 ',
Could you update the existing translation instead of creating a separate one?

2024-03-12 01:55 UTC, sj-h4 commented
@esauerbo 
Thank you for your review! I updated.

2024-03-29 18:11 UTC, reesscot commented on packages/ui/src/i18n/dictionaries/authenticator/ja.ts
> +  'Enter your Username': 'ユーザー名を入力 ',
@esauerbo Can we confirm that we don't use both lowercase and uppercase versions of this string?

2024-05-14 18:32 UTC, zchenwei approved these changes

2024-05-14 21:31 UTC, reesscot approved these changes

2024-05-14 21:56 UTC, merged