chore: update github workflows and add publishing tag on merge
aws-amplify/amplify-ui pull request #6260
Opened 2024-12-18 16:42 UTC by scanlonp

#### Description of changes

Add internal PR checks to the branch and add an npm tag for merges to the branch.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-12-18 17:03 UTC, jjarvisp requested changes
Instead of updating the workflow template file directly, I believe you need to copy the template to a new file in the `.github/workflows` directory and update with the branch name.

For example, create the new file in the workflows directory called `publish-email-mfa.yml`, copy the template into this file, and replace the references to `<BRANCH>` and `<TAG>`.

2024-12-18 20:06 UTC, jjarvisp approved these changes

2024-12-20 17:13 UTC, jordanvn commented on .github/workflows/email-mfa.publish.yml
> +      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
EOF newline?

2024-12-20 17:14 UTC, jordanvn commented on .github/workflows/email-mfa.publish.yml
> +      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
Nevermind, not really a concern given the intent of the change

2024-12-20 17:15 UTC, calebpollman approved these changes

2024-12-20 17:17 UTC, jordanvn approved these changes

2024-12-20 17:29 UTC, merged