Add changeset for Primitives + Theming Release
aws-amplify/amplify-ui pull request #747
Opened 2021-11-17 17:37 UTC by wlee221

*Issue #, if available:*

*Description of changes:* Adds changeset for primitives + theming release. Added a placeholder for now.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-11-17 17:50 UTC, ericclemmons approved these changes
I assume we'll make a final pass at the result in #596 ?  Or what's the best place to editorialize & "collapse" them all into our first major release?

(I recognize that subsequent releases are best for changesets to communicate patches/minors)

2021-11-17 17:54 UTC, wlee221 commented
@ericclemmons Right, the final pass will be at #596. It's just that it's the best practice to add new `changeset` on its own PRs. #596 are just a consumer of changesets (you get to *see* what happens, but not *modify*) and are not meant to be editoralized.

I opened this PR because this "major" bump `changeset` will be at the top of the changelogs and is important enough to be its own PR.

2021-11-17 17:57 UTC, ericclemmons requested changes
@dbanksdesign Since this will be top of the changelog, the bulk of it will be editorialized and likely cross-link to docs beyond summarizing what's in this.

2021-11-18 18:10 UTC, ericclemmons commented on .changeset/four-melons-double.md
> +Added new UI primtives and theming API
@dbanksdesign Can you add some content here that will headline our changelog?

I basically restated the goals & linked the RFC + docs:

https://github.com/aws-amplify/amplify-ui/pull/745/files

2021-11-18 20:31 UTC, Milan-Shah approved these changes

2021-11-18 20:32 UTC, slaymance approved these changes
🚢

2021-11-18 20:33 UTC, merged