Link troubleshooting guide from Authenticator docs
aws-amplify/amplify-ui pull request #976
Opened 2021-12-10 01:05 UTC by wlee221

*Issue #, if available:* closes #892, https://github.com/aws-amplify/amplify-ui/pull/904#issuecomment-987090224

*Description of changes:* Links troubleshooting from Authenticator docs, as this wasn't very visible and got a [feedback](https://github.com/aws-amplify/amplify-ui/pull/904#issuecomment-987090224) that this should be on Authenticator doc as well.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-12-10 01:16 UTC, reesscot requested changes
Just a spelling nit

2021-12-10 01:16 UTC, reesscot commented on docs/src/pages/components/authenticator/index.page.mdx
> +  you have any trouble building or running your appplication with authenticator.
nit: spelling
```suggestion
  you have any trouble building or running your application with Authenticator.
```

2021-12-10 01:16 UTC, wlee221 commented on docs/src/pages/components/authenticator/index.page.mdx
> +  you have any trouble building or running your appplication with authenticator.
Ahhhhhh

2021-12-10 01:45 UTC, ErikCH approved these changes

2021-12-13 17:44 UTC, reesscot approved these changes

2021-12-13 19:04 UTC, merged